// svelte-samurai/samurai-front/src/renderer/DebugBar.svelte
<script>
import store from '../store';
import { socket } from '../socket';
</script>

<div class="DebugBar">
  [Players] { $store.nbPlayers }
  | [Battles] 

  {#each $store.battles as battle (battle.id)}
    { battle.id } - 
  {/each}

  {#if $store.connected}
    <button on:click={() => socket().disconnect()}>Se deconnecter</button>
  {:else}
    <button on:click={() => socket().connect()}>Se connecter</button>
  {/if}
</div>

// vue-samurai/samurai-front/src/app/components/DebugBar.vue
<template>
  <Store #default="{ battles, nbPlayers, connected }">
    <Socket #default="{ disconnect, connect }">
      <div class="DebugBar">
        [Players] {{ nbPlayers }} 
        | [Battles] 
        <span :key="battle.id" v-for="battle in battles">
          {{ battle.id }}
        </span>

        <button v-if="connected" @click="disconnect">Se deconnecter</button>
        <button v-else @click="connect">Se connecter</button>
      </div>
    </Socket>
  </Store>
</template>
