// svelte-minesweeper/src/renderer/App.svelte
<script>
import { DEV } from '../constants';
import Minesweeper from './Minesweeper.svelte';
</script>


<div class="App">
  <Minesweeper/>
</div>
 
<style>
/* :global(:root) {
  --c-bg-1: #e9f5f5; 
}*/

:global(*, *:after, *:before) {
	box-sizing: border-box;
}

:global(html, body) {
	position: relative;
	width: 100%;
	height: 100%;
}

:global(body) {
	margin: 0;
  padding: 0;
}

.App {
  text-align: center; 
  padding: 50px 20px;
}
</style>

// pixi-dnd/overlay/App.vue
<template>
  <div class="App">
    <div class="sidebar"></div>
    <menu></menu>
  </div>
</template>

<style>
*, *:after, *:before {
  box-sizing: border-box;
}

html, body {
  padding: 0;
  margin: 0;
  width: 100%;
  height: 100%;
}

html {
  position: fixed;
  overflow: hidden;
}
</style>

<style lang="scss" scoped>
.sidebar {
  position: fixed;
  top: 0;
  left: 0;
  height: 100%;
  width: 4rem;
  background: white;
  box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.05);
}

menu {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  background: white;
  height: 3.5rem;
  border-bottom: 1px solid #DDDDDD;
  margin: 0;
}
</style>
