// svelte-samurai/samurai-front/src/routes/Game.svelte
<script>
import { onMount } from 'svelte';

let game$;

const scene = {
  img: '/background.png',
  width: 256,
  height: 222,
  scale: 1
};

onMount(autoScale);

function autoScale() {
  const container = game$.getBoundingClientRect()
  
  if(container.width < container.height) {
    scene.scale = container.width / scene.width;
  } else {
    scene.scale = container.height / scene.height;
  }
}
</script>

<svelte:head>
	<title>Samurai Kirby !</title>
</svelte:head>

<svelte:window on:resize={autoScale}/>

<div class="Game" bind:this={game$}>
  <div class="Game__body" style="{`
    background: url(${scene.img});
    width: ${scene.width}px;
    height: ${scene.height}px;
    transform: scale(${scene.scale})
  `}">
    <div class="kirby"></div>
  </div>
</div>

<style lang="less">
.Game {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}

.Game__body {
  position: relative;
  background-color: black;
  box-shadow: 0 0 9px rgba(0, 0, 0, 0.6), 0 0 0 9999px rgba(255, 255, 255, 0.4);
  border-radius: 5px;
}

.kirby {
  position: absolute;
  bottom: 10px;
  left: 10px;
  background: url('/samurai-kirby.png') no-repeat -9px -161px;
	width: 27px;
	height: 25px;
}
</style>

// beewan/beewan-front/src/components/Game.vue
<template>
  <div class="Game" :style="{ 'background-image': 'url(/levels/region-1.jpg)' }">
    <img src="/monsters/monster-12-idle.png" class="monster monster--left">
    <img src="/monsters/flip/monster-19-idle.png" class="monster monster--right">

    <div v-if="battle.go" class="go"></div>
    <div v-if="battleOver" class="battle-over">
      <span v-if="isWin">WINNER</span>
      <span v-else>LOSER</span>
    </div>

  </div>
</template>

<script>
import { getSocket } from '@/socket';

export default {
  props: ['battle'],
  
  computed: {
    battleOver() {
      return this.battle.winner !== undefined;
    },

    isWin() {
      return this.battleOver && this.battle.winner === getSocket().id;
    }
  },

  methods: {
    attack() {
      getSocket().emit('battle.attack');
    }
  },

  mounted () {
    document.addEventListener('keydown', this.attack);
  },

  beforeDestroy() {
    document.removeEventListener('keydown', this.attack);
  }
}
</script>

<style lang="scss" scoped>
.Game {
  position: relative;
  max-width: 700px;
  width: 100%;
  max-height: 500px;
  background-position: center center;
  background-repeat: no-repeat;
  background-size: cover;

  .monster {
    position: absolute;
    bottom: 50px;
    
    &--left {
      left: 100px;
    }

    &--right {
      right: 100px;
    }
  }

  .go {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translateX(-50%) translateY(-50%);
    height: 50px;
    width: 50px;
    border-radius: 50%;
    background-color: red;
  }

  .battle-over {
    position: absolute;
    top: 30px;
    width: 100%;
    text-align: center;
    font-size: 2rem;
    font-weight: bold;
    color: white;
    text-shadow: 2px 2px black;
  }
}
</style>
