// samurai-vue/samurai-front/src/app/App.vue
<template>
  <Store #default="{ searching, selectedBattle }">
    <Battle #default="{ join }">
      <div class="App">
        <DebugBar/>
        <div v-if="searching" class="matchmaking">
          En attente d'un noob...
        </div>
        <div v-else-if="!selectedBattle" class="matchmaking" @click="join">
          Faire la bagarre
        </div>
        <GameScene v-else :battle="selectedBattle"/>
      </div>
    </Battle>
  </Store>
</template>

<style lang="scss">
*, *:after, *:before {
  box-sizing: border-box;
}

body, html {
  padding: 0;
  margin: 0;
  height: 100%;
  width: 100%;
}

.App {
  background: url('/background.jpg');
  background-size: cover;
  height: 100%;
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 50px 100px;

  .GameScene {
    flex: 1;
  }

  .DebugBar {
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    height: 25px;
    background-color: rgba(0, 0, 0, 0.4);
  }

  .matchmaking {
    font-size: 2rem;
    font-weight: bold;
    color: white;
    text-shadow: 2px 2px black;
    cursor: pointer;
  }
}
</style>

// svelte-minesweeper/src/renderer/App.svelte
<script>
import { DEV } from '../constants';
import Minesweeper from '../game/Minesweeper';
import Board from './Board.svelte';

let minesweeper = new Minesweeper({
  rows: 16,
  cols: 30,
  mines: 99
});

const { store } = minesweeper;
</script>

<div class="App">
  <div class="scene">
    <Board minesweeper={minesweeper}/>
    
    {#if $store.completedAt}
      <div class="end-game">
        {$store.hasWon() ? 'Winner' : 'Loser' }
      </div>
    {/if}
  </div>
</div>
 
<style lang="scss">
:global(*, *:after, *:before) {
	box-sizing: border-box;
}

:global(html, body) {
	position: relative;
	width: 100%;
	height: 100%;
}

:global(body) {
	margin: 0;
  padding: 0;
}

.App {
  padding: 50px 20px;
  position: relative;
  text-align: center; 

  .scene {
    position: relative;
    display: inline-block;
  }

  .end-game {
    position: absolute;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 999;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(255, 255, 255, 0.3);
    color: white;
    text-shadow: 0 0 10px rgba(0,0,0,0.6);
    font-size: 73px;
    font-family: 'Asap', Arial, sans-serif;
  }
}
</style>
